[package]
name = "graphc"
version = "0.1.0"
edition = "2024"
authors = ["Maroš Grego <grego@math.cas.cz>", "Tomáš Vítek <vitek@math.cas.cz", "Thomas Willwacher <thomas.willwacher@math.ethz.ch>"]
description = "Tool for generating and working with the matrices of the forested graph complex"
license = "AGPL-3.0"

[dependencies]
argh = "0.1.13"
rayon = "1.11.0"
rustc-hash = "2.1.1"
